services:
  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-dn5&7cd2#ccmnnyazv6l!l7=#byr=lde0h5sfjwk1muw)j^zkf
      - DEBUG=True